### ISSUE TITLE
Changing Config.php site name / title doesn't reflect on pages

### ISSUE THREAD

**Issue by kevinfgordon** [stevemo/cpanel#10]
Hello,

Maybe I am missing something really stupid but I am having an issue changing items in config.php.

If I update

```
'site_config' => array(
    'site_name'   => 'Some site name',
    'title'       => 'Some title',
    'description' => 'Another description'
),
```

in config.php sitting in the vendor/stevemo/cpanel/src/config folder the changes don't reflect on the site itself.

**Comment by stevemo** [comment]
Hi,

Did you run in the terminal `php artisan cpanel:install` ? If so it as run for you the command `php artisan config:publish --package=stevemo/cpanel` This has created a copy of the package config file in app/config/packages/stevemo/cpanel/config.php. This is where you should change stuff. You should never modify code inside a third party package otherwise when you update the package your changes will be lost.
