### ISSUE TITLE
getting error when using cpanel:install

### ISSUE THREAD

**Issue by smshahinulislam** [stevemo/cpanel#30]
i have installed cpanel using composer and added service provider and aliases as instructed.after that when i try to use the command php artisan cpanel:install, i am getting an error.

```
{"error":{"type":"Symfony\\Component\\Debug\\Exception\\FatalErrorException","message":"Class 'Former\\FormerServiceProvider' not found","file":"F:\\xampp\\htdocs\\testproject\\bootstrap\\compiled.php","line":4219}}
```

I don't understand why former service provide is not found, its on the right place to be.

**Comment by stevebauman** [comment]
Before you install cpanel, you have to require Former in your composer.json file: `"anahkiasen/former": "dev-master"`

Since you ran the install already, you should look in your database and see if the migrations have taken place and rollback the migration using `php artisan migrate::rollback` on your project source so you can re-install the package without issues. The permissions table will be present if this has occured.

**Comment by stevemo** [comment]
updated master branch to fix former requirement issues
